import type { Metadata } from 'next'
import './globals.css'
import { ReactQueryProvider } from '@/app/providers/ReactQueryProvider'
import { Suspense } from 'react'
import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  preload: true,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Suspense>
            <div className="grid place-items-center bg-[url('/bg.png')] bg-cover bg-no-repeat">
              <div className="m-auto grid h-screen w-2/3 grid-cols-app grid-rows-app">
                {children}
              </div>
            </div>
          </Suspense>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
